apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-backend-ingress

spec:
  entryPoints:
    - http
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: gradewise-api-backend
          port: web
      middlewares:
        - name: strip-api-prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix

spec:
  stripPrefix:
    prefixes:
      - /api
