apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress

spec:
  entryPoints:
    - http
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: gradewise-frontend
          port: web
