apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata: { name: lti-ingress }
spec:
  entryPoints: [web, websecure]
  tls: {}
  routes:
    - match: PathPrefix(`/lti`)
      kind: Rule
      priority: 10000
      services:
        - name: gradewise-lti
          port: web