apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata: { name: lti-ingress }
spec:
  entryPoints: [websecure]
  tls: {}
  routes:
    - match: (Host(`dev.gradewise.org`) || Host(`jon-dev.gradewise.org`)) && PathPrefix(`/lti`)
      kind: Rule
      priority: 10000
      services:
        - name: gradewise-lti
          port: 8080