apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradewise-api-backend
  labels:
    app: gradewise-api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradewise-api-backend
  template:
    metadata:
      labels:
        app: gradewise-api-backend
    spec:
      containers:
        - name: gradewise-api-backend
          image: gradewise-api-backend:latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gradewise-api-backend
spec:
  selector:
    app: gradewise-api-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
