apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradewise-api-backend
  labels:
    app: gradewise-api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradewise-api-backend
  template:
    metadata:
      labels:
        app: gradewise-api-backend
    spec:
      containers:
        - name: gradewise-api-backend
          image: gradewise-api-backend:latest
          ports:
            - name: web
              containerPort: 8080
          # env:
          #   - name: PORT
          #     value: "80"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gradewise-api-backend
spec:
  selector:
    app: gradewise-api-backend
  ports:
    - name: web
      port: 80
      targetPort: web
